site_app/urls.py
from django.urls import path,re_path
# Import the views from the site_app
from site_app import views 
from django.urls import reverse_lazy

app_name='site_app'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('guest/list',views.GuestListView.as_view(),name='guest_list'),
    path('guest/new',views.GuestCreateView.as_view(),name='guest_new'),
    re_path(r'^guest/(?P<pk>\d+)/$',views.GuestDetailView.as_view(),name='guest_detail'),
]

wedding_project/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
# Import the views from the site_app
from site_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # Connect to the site_app urls.py file
    path('site_app/',include('site_app.urls'),name='site_app'),
    path('',views.IndexView.as_view()),
]

site_app/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.

class Guest(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    attending = models.BooleanField()
    full_name =str(first_name)+str(last_name)

    Veg = 'V'
    Beef = 'B'
    Chicken = 'C'
    meal_options = (
        (Veg, 'Vegetarian'),
        (Beef, 'Beef'),
        (Chicken, 'Chicken'),
    )
    meal_selection = models.CharField(max_length=1, choices=meal_options)


    def __str__(self):
        return self.first_name + ' ' + self.last_name
        

    def get_absolute_url(self):
        return reverse("site_app:detail", kwargs={"pk": self.pk})
    

site_app/forms.py
from django import forms
from site_app.models import Guest

class GuestForm(forms.ModelForm):

    class Meta():
        model = Guest
        fields = {'first_name','last_name', 'attending', 'meal_selection'}

site_app/views.py
from django.shortcuts import render, reverse
from django.urls import reverse_lazy
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView,TemplateView
from site_app.models import Guest
from django.contrib.auth.mixins import LoginRequiredMixin
from site_app.forms import GuestForm

# Create your views here.
class IndexView(TemplateView):
    template_name = 'site_app/index.html'

class GuestListView(ListView):
    context_object_name = 'guests'

    model = Guest

    # guest list

class GuestDetailView(DetailView):
    context_object_name = 'guest_detail'
    model = Guest
    template_name = 'site_app/guest_detail.html'


class GuestCreateView(CreateView, LoginRequiredMixin):
    login_url = '/login/'

    redirect_field_name = 'site_app/guest_detail.html'

    form_class = GuestForm

    model = Guest

site_app/templates/site_app/_accomodations.html
<div class="row" id="accomodations">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h1>Accomodations</h1>
    </div>
    <div class="col-md-2"></div>
</div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h3>*Kitchener-Waterloo Oktoberfest is on during our Wedding weekend*</h3>
        <img class="img-thumbnail" src="../../../static/images/oktoberfest.h" alt="Deer Ridge Gold Course">
    </div>
    <div class="col-md-2"></div>
</div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <p class="center" style="text-align:center;">PLAN AHEAD AND BOOK YOUR ACCOMODATIONS ASAP</p>
        <p>Kitchener–Waterloo Oktoberfest is an annual nine-day festival, running from October 11-19, 2019. It's
            Canada's Greatest Bavarian Festival and is the second-largest Oktoberfest in the world after Munich,
            Germany. Estimates indicate that the event attracts roughly 700,000 visitors to Waterloo Region each year.
        </p>
        <p> Our wedding weekend will be a busy one in the region and hotels are sure to book up fast - please plan
            accordingly.</p>
        <p>There are sure to be lots of 'R.I.D.E' programs out on the roads during Oktoberfest. Our venue offers FREE
            overnight parking. Please use it and get home safely.</p>

    </div>
    <div class="col-md-2"></div>
</div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h3>The Walper Hotel</h3>
        <img class="img-thumbnail" src="../../../static/images/walperhotel.h" alt="Deer Ridge Gold Course">
        <p class="center" style="text-align:center;">20 Queen St South, Kitchener, Ontario</p>
        <p class="center" style="text-align:center;">1-800-265-8749</p>
        <p>Indulge in history and old world charm at the freshly renovated Walper Hotel. With a stay at this historic
            hotel, one of the region's most historic buildings (a 1893 iconic landmark) you'll be centrally located
            right in the epicenter of Kitchener. Make yourself at home in this stunning boutique hotel, in one of the 92
            stunning rooms. Self-parking (subject to charges) is available onsite.</p>

        <p>Use code KMHWEDDING at the time of booking to book from our room block and to take advantage of our preferred
            group rate of $207.20/night + tax. Occupancy ranges from 2-4 people per room. Group rate is available until
            September 1st, while rooms last. Don't delay, book today!</p>
    </div>
    <div class="col-md-2"></div>
</div>

site_app/templates/site_app/_our_story.html
<!-- <p id="our_story"></p><br><br> -->

<h1 id="our_story">Our Story</h1>

<p class="pclass">
    Kim and Max fell hard and fast for one another while they were both living in Toronto. Had it not been for online dating, 
    chances are slim that these two would have connected in the real world!
</p> 

<p class="pclass">
    Kim, a career-focused Marketing gal, spent her post-University life living downtown Montreal for 5 years working at the 
    glitzy L’OREAL head office, followed by 5 years in Toronto working predominately in the natural health and wellness industry - a passion of hers. Max, 
    originally from Saint John, New Brunswick, spent his post-University years working and living at remote sites across the country, specifically in Fort 
    McMurray and in northern Manitoba, working in finance. Max quickly realized that he didn’t want to be away from Kim for three weeks each month for work 
    (which was the nature of his job) so he resigned and together they moved to Kitchener Waterloo (Kim’s hometown) for a fresh start.
</p>

<p class="pclass">
    Max went back to school in KW to pursue a passion of his – IT – and now works in the booming Waterloo tech industry. Kim also works locally in her field 
    of Marketing.
</p>

<p class="pclass">
    The happy couple and their adorable rescue dog Trixie Ann, are so thankful for the life they’ve built together and can’t wait to celebrate their wedding 
    this fall with their friends and family and to embark on their next chapter, marriage!
</p>

<h3>The Proposal</h3>

<p class="pclass">
    On September 22, 2018, which happened to be the first day of fall, Max popped the question! It was a beautiful sunny day and the couple was out walking 
    the dog on a trail in the woods in their neighbouhood, when Max pretended to have tripped and hurt himself... conveniently in the 'down on one knee' 
    position. A concerned Kim, up ahead with Trixie Ann, raced back to see if he was OK. He was faking it! Next thing she knew, he was pulling a ring 
    box out of his pocket.
</p>

site_app/templates/site_app/_the_wedding.html
<!-- <p id="the_wedding"></p><br><br> -->

<div class="row" id="the_wedding">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h1>The Wedding</h1>
    </div>
    <div class="col-md-2"></div>
</div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <img class="img-thumbnail" src="../../../static/images/deerridge.jpeg" alt="Deer Ridge Gold Course">
    </div>
    <div class="col-md-2"></div>
</div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <p class="center" style="text-align:center;">Saturday, October 19, 2019</p>
        <p class="center" style="text-align:center;">4:30 PM</p>
        <p><strong>Attire:</strong> Black Tie Welcome. Please include if you have food allergies in the notes section of the RSVP.
            Although we love your little ones, please note that this will be an adults-only celebration. We thank you
            for your understanding.</p>
    </div>
    <div class="col-md-2"></div>
</div>

site_app/templates/site_app/_wedding_party.html
<!-- <p id="wedding_party"></p><br><br> -->

<h1 id="wedding_party">Wedding Party</h1>

<div>
    <!-- <div class="row">
        <div class="col-md-6">
            <h3>Bridesmaids</h3>
        </div>
        <div class="col-md-6">
            <h3>Groomsmen</h3>
        </div>
    </div> -->
    <div class="row">
        <div class="col-md-6 col-sm-6">
            <img class="img-circle" src="../../../static/images/kellyheadshot.jpg" alt="headshot of Kelly" width="200"
                height="200">
            <h4>Kelly Snyder - Maid of Honour</h4>
            <p>
                Kelly and Kim are not only sisters, but best friends. Kim was Kelly’s Maid of Honour at her gorgeous
                fall 2017 wedding
                and Kelly is excited to do the honours for Kim. Kelly has provided tremendous support to Kim throughout
                the wedding
                planning journey, helping her to find vendors, make tough decisions, give advice and ultimately plan her
                dream wedding.
                Kelly was also a big help to Max, who enlisted her help to pick out the perfect engagement ring (smart
                man)! She is a
                Realtor in KW and also sold Kim and Max their home, which they have happily been living in since March
                2018. These
                sisters have a special bond and are so thankful for their amazing relationship!
            </p>
        </div>
        <div class="col-md-6 col-sm-6">
            <img class="img-circle" src="../../../static/images/carlheadshot.jpg" alt="headshot of Carl" width="200"
                height="200">
            <h4>Carl Wickstrom - Best Man</h4>
            <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Commodi ipsam pariatur, reiciendis quia
                voluptates veniam amet rerum obcaecati expedita fugiat. Maxime eius quam accusantium earum labore iste
                repellat rem qui.
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <img class="img-circle" src="../../../static/images/lindyheadshot.jpg" alt="headshot of Kelly" width="200"
                height="200">
            <h4>Lindy Herrington - Bridesmaid</h4>
            <p>
                Lindy is the middle child in the Herrington family and was an obvious choice to be one of Kim’s
                bridesmaids! Max and Lindy have always had a unique relationship, bonding over such things as Harry
                Potter and Star Wars. Only 2 years younger than Max, the two had lots of mutual friends over the years
                and were even roommates at one point while living in Halifax. Lindy lives and works in Toronto as a
                lawyer. Kim is looking forward to officially becoming sisters-in-law with the Herrington girls!
            </p>
        </div>
        <div class="col-md-6">
            <img class="img-circle" src="../../../static/images/chrisheadshot.jpg" alt="headshot of Chris" width="200"
                height="200">
            <h4>Chris Blair - Groomsman</h4>
            <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Commodi ipsam pariatur, reiciendis quia
                voluptates veniam amet rerum obcaecati expedita fugiat. Maxime eius quam accusantium earum labore iste
                repellat rem qui.
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <img class="img-circle" src="../../../static/images/taylorheadshot.jpg" alt="headshot of Taylor" width="200"
                height="200">
            <h4>Taylor Herrington - Bridesmaid</h4>
            <p>
                Taylor is the youngest Herrington sister and has a special place in Max’s heart - he affectionately
                refers to her as Tay Tay. Since Taylor graduated from Queens University, she's spent the last two years
                working at Trinity College in Aurora, the private school she attended on an ice hockey scholarship. She
                looks forward to starting Teacher’s College in the fall at Trent.
            </p>
        </div>
        <div class="col-md-6">
            <img class="img-circle" src="../../../static/images/kyleheadshot.jpg" alt="headshot of Kyle" width="200"
                height="200">
            <h4>Kyle Rogers - Groomsman</h4>
            <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Commodi ipsam pariatur, reiciendis quia
                voluptates veniam amet rerum obcaecati expedita fugiat. Maxime eius quam accusantium earum labore iste
                repellat rem qui.
            </p>
        </div>
    </div>


    <div class="row">
        <div class="col-md-6">
            <img class="img-circle" src="../../../static/images/ashleyheadshot.jpg" alt="headshot of Ashley" width="200"
                height="200">
            <h4>Ashely Mojito - Bridesmaid</h4>
            <p>
                Ashley and Kim met as colleagues at L’Oreal, working downtown Montreal. They hit it off immediately and
                have been very close friends ever since. Every time Kim is with Ashley, it’s always a lot of laughs
                (Ashley is one hilarious gal!) and a fun time. Ashley’s super positive, bubbly personality is
                contagious. Kim is so thankful to have Ashley by her side on her wedding day and for her friendship.
                Ashley, originally from Calgary, lives in Toronto with her husband John and their two children Timothy
                and Anne-Marie and works as a Sales Manager. SHE HAS MASSIVE MOM BOOBS
            </p>
        </div>
        <div class="col-md-6">
            <img class="img-circle" src="../../../static/images/jasonheadshot.jpg" alt="headshot of Jason" width="200"
                height="200">
            <h4>Jason Hackett - Groomsman</h4>
            <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Commodi ipsam pariatur, reiciendis quia
                voluptates veniam amet rerum obcaecati expedita fugiat. Maxime eius quam accusantium earum labore iste
                repellat rem qui.
            </p>
        </div>
    </div>

</div>

site_app/templates/site_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Guest List</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="../../../static/css/master.css">
    <link href="https://fonts.googleapis.com/css?family=Ruge+Boogie|Ruthie|Special+Elite" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-default" style="background-color: transparent; border: none; margin-top: 1em;">
    <div class="container-fluid">

        <div class="navbar-header" style="text-align:center">
            <button type="button" class="navbar-toggle hamburger" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav menu">
                <li><a href="{% url 'site_app:index'%}#our_story">Our Story</a></li>
                <li><a href="{% url 'site_app:index'%}#the_wedding">The Wedding</a></li>
                <li><a href="{% url 'site_app:index'%}#wedding_party">Wedding Party</a></li>
                <li><a href="{% url 'site_app:index'%}#accomodations">Accomodations</a></li>
                <li><a href="{% url 'site_app:index'%}#the_wedding">RSVP</a></li>
            </ul>
        </div>
    </div>

    </nav>
    <div class="container">
        {% block bodyblock %}
        {% endblock bodyblock %}
    </div>
    <nav class="navbar navbar-default navbar-collapse navbar-fixed-bottom" style="background-color:white;">
        <ul class="nav navbar-nav center">
            <li><a href="{% url 'site_app:index'%}#top">Back to Top</a></li>
        </ul>
    </nav>

</body>

</html>

site_app/templates/site_app/guest_detail.html
{% extends "site_app/base.html" %}
 {% block bodyblock %}
    <h3>Welcome to the guest details page for {{guest_detail.first_name}} {{guest_detail.last_name}}</h3>

    {% if guest_detail.attending == True %}

    <p>Attending</p>
     
        {% if guest_detail.meal_selection == 'C' %}
            <p>Meal Choice: Chicken</p>

        {% elif guest_detail.meal_selection == 'V' %}
            <p>Meal Choice: Vegetarion</p>

        {% else %}
            <p>Meal Choice: Beef</p>
        {% endif %}

    {% else %}

        <p>Not Attending</p>

    {% endif %}

    
 {% endblock bodyblock %}

site_app/templates/site_app/guest_list.html
{% extends "site_app/base.html" %}
{% block bodyblock %}
  <h2>Welcome to the guest list page</h2>

  <table class="table">
      <tr>
          <th scope="col">Last Name</th>
          <th scope="col">First Name</th>
      </tr>
  {% for guest in guests %}
      <tr>
          <td><a href="{{guest.id}}">{{guest.last_name}}</a></td>
          <td><a href="{{guest.id}}">{{guest.first_name}}</a></td>
      </tr>
  {% endfor %}
{% endblock bodyblock %}

site_app/templates/site_app/index.html
{% extends "site_app/base.html" %}

{% block bodyblock %}
  <div class="jumbotron background">
      <h1 class="headerh1">Kimberly & Maxwell</h1>
      <p class="pjumbo">October 19, 2018 - Kitchener, Ontario</p>
  </div>

{% include "site_app/_our_story.html" %}

{% include "site_app/_the_wedding.html" %}

{% include "site_app/_wedding_party.html" %}

{% include "site_app/_accomodations.html" %}

{% endblock bodyblock %}